### ISSUE TITLE
Lesson 15 walker php problem

### ISSUE THREAD

**Issue by webspecialist** [Alecaddd/WordPress101#4]
I got a problem in admin view and my page the follow php error:

Warning: Declaration of Walker_Nav_Primary::start_lvl(&$output, $depth) should be compatible with Walker_Nav_Menu::start_lvl(&$output, $depth = 0, $args = Array) in C:\wamp64\www\wordtest\wp-content\themes\awesometheme\inc\walker.php on line 0

Any ideas?

**Comment by Alecaddd** [comment]
WordPress updated the requirements for the Walker Nav Class since I did the tutorials, now the arguments of the method required a default declaration. I updated the source code to reflect these changes.
